// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_uyg.Data;

#nullable disable

namespace web_uyg.Migrations
{
    [DbContext(typeof(AlisverisListesiContext))]
    [Migration("20250120204259_MiktarBirimiEklendi")]
    partial class MiktarBirimiEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("web_uyg.Models.AlisverisUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlındiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiktarBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("AlisverisListesi");
                });

            modelBuilder.Entity("web_uyg.Models.FavoriUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VarsayilanMiktar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FavoriUrunler");
                });

            modelBuilder.Entity("web_uyg.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Taze meyve ve sebzeler",
                            Ad = "Meyve & Sebze"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Süt, peynir, yoğurt vb.",
                            Ad = "Süt & Süt Ürünleri"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Bakliyat, un, şeker vb.",
                            Ad = "Temel Gıda"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Temizlik malzemeleri",
                            Ad = "Temizlik"
                        });
                });

            modelBuilder.Entity("web_uyg.Models.AlisverisUrunu", b =>
                {
                    b.HasOne("web_uyg.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("web_uyg.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
