// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_uyg.Data;

#nullable disable

namespace web_uyg.Migrations
{
    [DbContext(typeof(AlisverisListesiContext))]
    partial class AlisverisListesiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("web_uyg.Models.AlisverisListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonDegistirilmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VarsayilanMi");

                    b.ToTable("AlisverisListeler");
                });

            modelBuilder.Entity("web_uyg.Models.AlisverisUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlındiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiktarBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Not")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiraNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("ListeId", "SiraNo");

                    b.ToTable("AlisverisListesi");
                });

            modelBuilder.Entity("web_uyg.Models.FavoriUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VarsayilanMiktar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FavoriUrunler");
                });

            modelBuilder.Entity("web_uyg.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Taze meyve ve sebzeler",
                            Ad = "Meyve & Sebze"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Süt, peynir, yoğurt vb.",
                            Ad = "Süt & Süt Ürünleri"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Bakliyat, un, şeker vb.",
                            Ad = "Temel Gıda"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Temizlik malzemeleri",
                            Ad = "Temizlik"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Sıcak ve soğuk içecekler",
                            Ad = "İçecek"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Tatlı ve tatlı ürünler",
                            Ad = "Tatlı"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Kahvaltı için gerekli ürünler",
                            Ad = "Kahvaltı"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Yiyecek ürünleri",
                            Ad = "Yiyecek"
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Süs eşyaları",
                            Ad = "Süs Eşyası"
                        });
                });

            modelBuilder.Entity("web_uyg.Models.AlisverisUrunu", b =>
                {
                    b.HasOne("web_uyg.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_uyg.Models.AlisverisListesi", "Liste")
                        .WithMany("Urunler")
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Liste");
                });

            modelBuilder.Entity("web_uyg.Models.AlisverisListesi", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("web_uyg.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
